Feature/refactoring
Dechea/Fauna-Rule-Engine pull request #2
Opened 2022-11-02 10:12 UTC by mbauer55

2022-11-02 10:24 UTC, madhavKD commented on buildRule.js
> +  console.log(ruleValue)
Remove log, if not required

2022-11-02 10:25 UTC, madhavKD commented on buildRule.js
> +  // })
Remove theses commented lines, if not required

2022-11-02 10:26 UTC, madhavKD commented on buildRule.js
> +// build(requestBodyCondition)
Remove these commented code, if not required

2022-11-02 10:26 UTC, madhavKD commented on buildRule.js
>    // console.log(flatt)
Remove this

2022-11-10 05:58 UTC, firehudson commented on buildParts.js
> +const { convertGraphQLToFQL } = require("./graphqlToFQLConverter");
Format file with indentation of 2 spacing

2022-11-10 06:02 UTC, firehudson commented on buildParts.js
> +			if (source?.type?.toLowerCase() === 'fact')
Store `'fact'` in constant variable like this `const FACT = 'fact'` and use variable everywhere in the code

2022-11-10 06:05 UTC, firehudson commented on buildParts.js
> +const getCorrectOperator = (operator) => {
Convert this function in single line arrow function

2022-11-10 06:06 UTC, firehudson commented on buildParts.js
> +	if (type.toLowerCase() === 'fact')
Replace `'fact'` with constant variable

2022-11-10 06:09 UTC, firehudson commented on buildParts.js
> +
Remove empty line

2022-11-10 06:13 UTC, firehudson commented on buildParts.js
> +		if (updatedKey !== undefined) {
Replace `(updatedKey !== undefined)` with `(updatedKey)`

2022-11-10 06:15 UTC, firehudson commented on buildParts.js
> +			) {
Replace `if (
				inputObject.source?.type !== undefined
				&& inputObject.source?.name !== undefined
				&& inputObject.source?.value !== undefined
				&& 'comparator' in inputObject
				&& inputObject.target?.type !== undefined
				&& inputObject.target?.value !== undefined
			) {`

with 
`if (
				inputObject.source?.type
				&& inputObject.source?.name
				&& inputObject.source?.value
				&& 'comparator' in inputObject
				&& inputObject.target?.type
				&& inputObject.target?.value
			) {
`

2022-11-10 06:16 UTC, firehudson commented on buildParts.js
> +
Remove empty line

2022-11-10 06:19 UTC, firehudson commented on buildParts.js
> +	//
Remove this line

2022-11-10 06:22 UTC, firehudson commented on buildParts.js
> +	if (variableNames.length === 0) {
Replace `if (variableNames.length === 0)` with `if (!variableNames.length)`

2022-11-10 06:22 UTC, firehudson commented on buildParts.js
> +
Remove empty line

2022-11-10 06:23 UTC, firehudson commented on buildParts.js
> +
Remove empty line

2022-11-10 06:40 UTC, firehudson commented on buildParts.js
> +	let conditionName;
Move all variable declaration at top of file

2022-11-10 06:41 UTC, firehudson commented on buildParts.js
> +
Remove empty line

2022-11-10 06:42 UTC, firehudson commented on buildParts.js
> +
Remove empty line

2022-11-10 06:43 UTC, firehudson commented on buildParts.js
> +const createFunction = (functionName, functionBody) => {
Convert function into single line arrow function

2022-11-10 06:45 UTC, firehudson commented on buildRule.js
> +
Remove this code if not required

2022-11-10 06:46 UTC, firehudson commented on buildRule.js
> +// build(requestBodyFact)
Remove commented code if not required

2022-11-10 07:00 UTC, firehudson requested changes

2022-11-10 07:00 UTC, firehudson commented on buildParts.js
> +		const updatedKey = keys[updatedAmount-1];
```suggestion
		const updatedKey = keys[updatedAmount - 1];
```

2022-11-10 07:00 UTC, firehudson commented on buildParts.js
> +
in JS conventionally we don't leave empty line at the start of function body

2022-11-10 07:01 UTC, firehudson requested changes

2022-11-10 07:01 UTC, firehudson commented on buildParts.js
> +}
Let's add EOF empty line

2022-11-14 10:23 UTC, merged